/**
 * Regenerates src/components/terminal/xterm-vendor.ts by inlining the installed
 * xterm.js + xterm-addon-fit builds and the xterm stylesheet, so the terminal
 * WebView works fully offline (no CDN). Run after bumping the xterm versions:
 *
 *   node scripts/vendor-xterm.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))

const xtermDir = dirname(require.resolve('xterm/package.json'))
const fitDir = dirname(require.resolve('xterm-addon-fit/package.json'))
const xtermVersion = require('xterm/package.json').version
const fitVersion = require('xterm-addon-fit/package.json').version

const read = (p) => readFileSync(p, 'utf8')

// Avoid prematurely terminating the surrounding <script>/<style> tags when the
// content is inlined into the HTML document.
const safeScript = (s) => s.replace(/<\/script/gi, '<\\/script')
const safeStyle = (s) => s.replace(/<\/style/gi, '<\\/style')

const css = safeStyle(read(join(xtermDir, 'css', 'xterm.css')))
const xtermJs = safeScript(read(join(xtermDir, 'lib', 'xterm.js')))
const fitJs = safeScript(read(join(fitDir, 'lib', 'xterm-addon-fit.js')))

const out = `/**
 * AUTO-GENERATED by scripts/vendor-xterm.mjs — do not edit by hand.
 * Vendored xterm.js ${xtermVersion} + xterm-addon-fit ${fitVersion} for offline WebView use.
 */

export const XTERM_CSS = ${JSON.stringify(css)}

export const XTERM_JS = ${JSON.stringify(xtermJs)}

export const XTERM_FIT_JS = ${JSON.stringify(fitJs)}
`

const target = join(here, '..', 'src', 'components', 'terminal', 'xterm-vendor.ts')
writeFileSync(target, out)
console.log(`Wrote ${target} (xterm ${xtermVersion}, fit ${fitVersion})`)
